# Generated by Django 4.1.7 on 2023-03-09 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Phone Number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True, verbose_name='Gender')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profile Picture')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='ProfileUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('first_name', 'first_name'), ('last_name', 'last_name'), ('email', 'email'), ('phone_number', 'phone_number'), ('date_of_birth', 'date_of_birth'), ('gender', 'gender'), ('address1', 'address1'), ('address2', 'address2'), ('city', 'city'), ('pincode', 'pincode'), ('state', 'state'), ('latitude', 'latitude'), ('longitude', 'longitude'), ('profile_picture', 'profile_picture')], max_length=50, verbose_name='Update Type')),
                ('updated_from', models.CharField(max_length=100, verbose_name='Updated From')),
                ('updated_to', models.CharField(max_length=100, verbose_name='Updated To')),
                ('updated_at', models.DateTimeField(verbose_name='Updated At')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile Update',
                'verbose_name_plural': 'Profile Updates',
            },
        ),
        migrations.CreateModel(
            name='HomeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='Created At')),
                ('address1', models.CharField(max_length=50, verbose_name='Address 1')),
                ('address2', models.CharField(max_length=50, verbose_name='Address 2')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('pincode', models.CharField(max_length=6, verbose_name='Postal Code')),
                ('state', models.CharField(choices=[('AN', 'Andaman and Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('CH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('LA', 'Ladakh'), ('LD', 'Lakshadweep'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OD', 'Odisha'), ('PB', 'Punjab'), ('PY', 'Pondicherry'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TS', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal')], max_length=2, verbose_name='State')),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='Longitude')),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='Latitude')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='User')),
            ],
        ),
    ]
