# Generated by Django 4.1.7 on 2023-02-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='phone_number',
            field=models.CharField(default=6239940285, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='pincode',
            field=models.CharField(default=143001, max_length=6),
            preserve_default=False,
        ),
    ]
