# Generated by Django 4.1.7 on 2023-03-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_location_delete_homeaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(upload_to='profile-pictures', verbose_name='Profile Picture'),
        ),
    ]
