# Generated by Django 4.1.7 on 2023-03-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_firebase_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firebase_uid',
            new_name='user',
        ),
    ]
