# Generated by Django 4.1.7 on 2023-03-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_firebase_uid_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='State/Territory'),
        ),
    ]
