# Generated by Django 4.1.7 on 2023-04-07 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_location_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='pincode',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinLengthValidator(6)], verbose_name='Postal Code'),
        ),
        migrations.DeleteModel(
            name='Pincode',
        ),
    ]
