# Generated by Django 4.1.7 on 2023-02-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_customuserprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuserprofile',
            options={'verbose_name': ('User Profile',), 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='first_name',
            field=models.CharField(max_length=45, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Others')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='last_name',
            field=models.CharField(max_length=45, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitutde'),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='phone_number',
            field=models.CharField(max_length=10, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='pincode',
            field=models.CharField(max_length=6, verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='secondary_phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Alternate Mobile Number'),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='state',
            field=models.CharField(choices=[('AN', 'Andaman and Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('CH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('LA', 'Ladakh'), ('LD', 'Lakshadweep'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OD', 'Odisha'), ('PB', 'Punjab'), ('PY', 'Pondicherry'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TS', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal')], max_length=2, verbose_name='State'),
        ),
    ]
