# Generated by Django 4.2 on 2023-04-11 16:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_number', models.PositiveBigIntegerField(unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{12}$')], verbose_name='Aadhar Number')),
                ('pan', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-z]{5}[0-9]{4}[a-zA-Z]{1}$')], verbose_name='Permanent Account Number')),
                ('requests_completed', models.IntegerField(default=0, verbose_name='Requests Completed')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Rating')),
                ('worker_type', models.CharField(choices=[('electrician', 'electrician'), ('plumber', 'plumber')], max_length=15)),
                ('is_available', models.BooleanField(default=False, verbose_name='Is Available')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
            },
        ),
    ]
