# Generated by Django 4.2 on 2023-04-11 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('uid', models.BigAutoField(db_column='uid', primary_key=True, serialize=False, verbose_name='User ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Phone Number')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Is Email Verified')),
                ('signed_up', models.DateTimeField(verbose_name='Signed Up')),
                ('signup_platform', models.CharField(choices=[('django', 'Django'), ('flutter', 'Flutter')], max_length=10, verbose_name='Signup Platform')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Last Activity')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='URLCode',
            fields=[
                ('code', models.CharField(editable=False, max_length=55, primary_key=True, serialize=False, verbose_name='Code')),
                ('type_of_link', models.CharField(max_length=100, verbose_name='Type of Link')),
                ('generated_at', models.DateTimeField(verbose_name='Generated At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='MobileAuthToken',
            fields=[
                ('token', models.CharField(editable=False, max_length=55, primary_key=True, serialize=False, verbose_name='Token')),
                ('generated_at', models.DateTimeField(verbose_name='Generated At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('is_revoked', models.BooleanField(verbose_name='Is Revoked')),
                ('last_used', models.DateTimeField(verbose_name='Last Used')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
