# Generated by Django 4.1.7 on 2023-03-06 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Is Email Verified'),
        ),
        migrations.CreateModel(
            name='URLCode',
            fields=[
                ('code', models.CharField(editable=False, max_length=55, primary_key=True, serialize=False, verbose_name='Code')),
                ('type_of_link', models.CharField(max_length=100, verbose_name='Type of Link')),
                ('generated_at', models.DateTimeField(verbose_name='Generated At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
