# Generated by Django 4.1.7 on 2023-03-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uid',
            field=models.BigAutoField(db_column='uid', primary_key=True, serialize=False, verbose_name='User ID'),
        ),
    ]
