# Generated by Django 4.2 on 2023-04-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uid',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='User ID'),
        ),
    ]
