# Generated by Django 4.1.7 on 2023-03-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfirebaseuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
