# Generated by Django 4.1.7 on 2023-02-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customfirebaseuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfirebaseuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Activity'),
        ),
        migrations.AlterField(
            model_name='customfirebaseuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Login'),
        ),
    ]
