# Generated by Django 4.1.7 on 2023-03-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_is_email_verified_urlcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='signup_platform',
            field=models.CharField(choices=[('django', 'Django'), ('flutter', 'Flutter')], default='django', max_length=10, verbose_name='Signup Platform'),
            preserve_default=False,
        ),
    ]
