# Generated by Django 4.1.7 on 2023-03-10 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAuthToken',
            fields=[
                ('token', models.CharField(editable=False, max_length=55, primary_key=True, serialize=False, verbose_name='Token')),
                ('generated_at', models.DateTimeField(verbose_name='Generated At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('is_revoked', models.BooleanField(verbose_name='Is Revoked')),
                ('last_used', models.DateTimeField(verbose_name='Last Used')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
