# Generated by Django 4.1.7 on 2023-03-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_alter_request_forwarded_to'),
        ('authentication', '0004_worker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
