# Generated by Django 4.1.7 on 2023-02-19 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_customuserprofile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_required', models.CharField(choices=[('plumber', 'Plumbing'), ('electrician', 'Electrical Work')], max_length=20)),
                ('issue', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=90)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('secondary_phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=250)),
                ('pincode', models.CharField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.customuserprofile')),
            ],
        ),
    ]
