# Generated by Django 4.1.7 on 2023-02-19 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_customuserprofile_user'),
        ('requests', '0002_alter_request_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.customuserprofile'),
        ),
    ]
