# Generated by Django 4.1.7 on 2023-02-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_alter_request_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='forwarded_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='is_closed',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='is_forwarded',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
