# Generated by Django 4.1.7 on 2023-02-28 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('request_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Request ID')),
                ('time_of_request', models.DateTimeField(verbose_name='Time of Request')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='profiles.profilemodel', verbose_name='firebase_uid')),
            ],
        ),
    ]
