# Generated by Django 4.2 on 2023-04-11 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_needed', models.CharField(choices=[('Installation', 'Installation'), ('Maintenance', 'Maintenance'), ('Repair', 'Repair'), ('Consultation', 'Consultation')], max_length=50, verbose_name='Service Needed')),
                ('appliance', models.CharField(choices=[('Lighting', 'Lighting'), ('Outlets/Switches', 'Outlets/Switches'), ('Ceiling Fans', 'Ceiling Fans'), ('Circuit Breakers', 'Circuit Breakers (MCB)'), ('Electrical Panels', 'Electrical Panels'), ('Wiring', 'Wiring'), ('Air Conditioning', 'Air Conditioning'), ('Refrigerator', 'Refrigerator'), ('Other', 'Other'), ('Lighting', 'Lighting'), ('Outlets/Switches', 'Outlets/Switches'), ('Ceiling Fans', 'Ceiling Fans'), ('Circuit Breakers', 'Circuit Breakers (MCB)'), ('Electrical Panels', 'Electrical Panels'), ('Wiring', 'Wiring'), ('Air Conditioning', 'Air Conditioning'), ('Refrigerator', 'Refrigerator'), ('Other', 'Other'), ('Lighting', 'Lighting'), ('Ceiling Fans', 'Ceiling Fans'), ('Electrical Panels', 'Electrical Panels'), ('Air Conditioning', 'Air Conditioning'), ('Refrigerator', 'Refrigerator'), ('Other', 'Other'), ('General Inquiry', 'General Inquiry')], max_length=100, verbose_name='Appliance')),
                ('time_of_request', models.DateTimeField(verbose_name='Time of Request')),
                ('is_emergency', models.BooleanField(default=False, verbose_name='Is Emergency')),
                ('issue', models.TextField(verbose_name='Issue')),
                ('is_forwarded', models.BooleanField(default=False, verbose_name='Is Forwarded')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Is Closed')),
                ('forwarded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worker.worker', verbose_name='Worker')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.location', verbose_name='Location')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='request.request', verbose_name='Request ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Rating')),
                ('likely_to_recommend', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Likely to Recommend')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback')),
                ('time_of_feedback', models.DateTimeField(verbose_name='Time of Feedback')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
