# Generated by Django 4.1.7 on 2023-03-05 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='firebase_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.profile', verbose_name='Firebase User ID'),
        ),
    ]
