# Generated by Django 4.1.7 on 2023-02-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='request_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='Request ID'),
        ),
    ]
