# Generated by Django 4.1.7 on 2023-03-20 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_worker'),
        ('request', '0002_remove_requestmodel_address_remove_requestmodel_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='likely_to_recommend',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Likely to Recommend'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Rating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='forwarded_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.worker', verbose_name='Worker ID'),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback'),
        ),
    ]
