# Generated by Django 4.1.7 on 2023-03-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_alter_requestmodel_firebase_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestmodel',
            old_name='firebase_uid',
            new_name='user',
        ),
    ]
