# Generated by Django 4.1.7 on 2023-03-20 11:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_worker'),
        ('profiles', '0004_alter_profile_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0003_remove_feedbackmodel_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbackModel',
            new_name='Feedback',
        ),
        migrations.RenameModel(
            old_name='RequestModel',
            new_name='Request',
        ),
    ]
