# Generated by Django 4.1.7 on 2023-03-25 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
        ('request', '0004_rename_feedbackmodel_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='forwarded_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worker.worker', verbose_name='Worker ID'),
        ),
    ]
